export const navigationLinks = [
  { name: 'About', path: '/about' },
  { name: 'Programs', path: '/programs' },
  { name: 'Our Team', path: '/our-team' },
  { name: 'Gallery', path: '/gallery' },
  { name: 'Library', path: 'https://doulosseminarylibrary.blogspot.com/', external: true },
  { name: 'Contact', path: '/contact' },
];

export const footerLinks = {
  company: [
    { name: 'About Us', path: '/about' },
    { name: 'Our Team', path: '/our-team' },
    { name: 'Leadership', path: '/our-team' },
  ],
  services: [
    { name: 'Programs', path: '/programs' },
    { name: 'Events', path: '/gallery' },
    { name: 'Contact', path: '/contact' },
  ],
};

export const contactInfo = {
  email: 'dts.thiruvalla@gmail.com',
  phone: '+91-9630426566',
  address: 'Doulos Theological Seminary, Thiruvalla P.O. Thiruvalla',
  principalPhone: '+91-9847599603',
  additionalPhone: '+91-9400130835',
  principalEmail: 'benson.yohanan@gmail.com',
  social: {
    instagram: '#',
    facebook: '#',
  },
};

export const teamData = {
  principal: {
    name: 'Pastor Dr. Benssen V. Yohannan',
    position: 'Principal & Director',
    email: 'benson.yohanan@gmail.com',
    phone: '+91 98475 99603',
    qualifications: ['BA', 'M.Div', 'M.Th', 'D.Min', 'PhD'],
    image: '/src/assets/BenssenYohannan.svg',
  },
  administrators: [
    {
      name: 'Rev Aju Alex',
      position: 'Academic Dean',
      qualification: 'M.Th, M.Div',
      image: '/placeholder-admin1.jpg',
    },
    {
      name: 'Lijo Benssen',
      position: 'Administrator - Counselling Institute',
      qualification: 'M.A Psychology',
      image: '/placeholder-admin2.jpg',
    },
    {
      name: 'Dr. Sarah Johnson',
      position: 'Registrar',
      qualification: 'Ph.D, M.Th',
      image: '/placeholder-admin3.jpg',
    },
    {
      name: 'Rev. Michael Thomas',
      position: 'Dean of Students',
      qualification: 'M.Div, M.Th',
      image: '/placeholder-admin4.jpg',
    },
  ],
  faculty: [
    {
      name: 'Dr. John Wesley',
      qualification: 'Ph.D Systematic Theology',
      image: '/placeholder-faculty1.jpg',
    },
    {
      name: 'Prof. Mary Elizabeth',
      qualification: 'M.Th Biblical Studies',
      image: '/placeholder-faculty2.jpg',
    },
    {
      name: 'Rev. David Kumar',
      qualification: 'M.Div Practical Theology',
      image: '/placeholder-faculty3.jpg',
    },
    {
      name: 'Dr. Rachel Philip',
      qualification: 'Ph.D Church History',
      image: '/placeholder-faculty4.jpg',
    },
    {
      name: 'Prof. James Mathew',
      qualification: 'M.Th Missiology',
      image: '/placeholder-faculty5.jpg',
    },
    {
      name: 'Dr. Grace Samuel',
      qualification: 'Ph.D Christian Counselling',
      image: '/placeholder-faculty6.jpg',
    },
  ],
  officeTeam: [
    {
      name: 'Mrs. Priya Nair',
      position: 'Administrative Assistant',
      phone: '+91-9876543210',
      image: '/placeholder-office1.jpg',
    },
    {
      name: 'Mr. Ravi Kumar',
      position: 'Accounts Officer',
      phone: '+91-9876543211',
      image: '/placeholder-office2.jpg',
    },
    {
      name: 'Mrs. Suma Thomas',
      position: 'Library Assistant',
      phone: '+91-9876543212',
      image: '/placeholder-office3.jpg',
    },
    {
      name: 'Mr. Joseph Abraham',
      position: 'IT Support',
      phone: '+91-9876543213',
      image: '/placeholder-office4.jpg',
    },
  ],
};

export const programsData = {
  theological: [
    {
      id: 'bth',
      name: 'Bachelor of Theology (B.Th.)',
      description: 'Comprehensive foundation in biblical studies and theology',
      image: '/placeholder-program1.jpg',
      syllabus: {
        'First Year': {
          'Sem I': [
            { subject: 'NT Survey I', credits: 3 },
            { subject: 'Systematic Theology I', credits: 3 },
            { subject: 'Church History I', credits: 3 },
            { subject: 'English I', credits: 2 },
            { subject: 'Praise & Worship', credits: 2 },
            { subject: 'Life of Christ', credits: 2 },
            { subject: 'Church Ministry', credits: 2 },
            { subject: 'Personal Evangelism', credits: 2 },
          ],
          'Sem II': [
            { subject: 'NT Survey II', credits: 3 },
            { subject: 'Systematic Theology II', credits: 3 },
            { subject: 'Church History II', credits: 3 },
            { subject: 'English II', credits: 2 },
            { subject: 'World Church History', credits: 3 },
            { subject: 'Outreach Ministry', credits: 2 },
            { subject: 'Teaching Method', credits: 2 },
            { subject: 'Comparative Religion', credits: 2 },
          ],
        },
        'Second Year': {
          'Sem III': [
            { subject: 'OT Survey I', credits: 3 },
            { subject: 'Systematic Theology III', credits: 3 },
            { subject: 'Contemporary Church History', credits: 3 },
            { subject: 'Christian Evidence', credits: 2 },
            { subject: 'English III', credits: 2 },
            { subject: 'Poetical Books', credits: 3 },
            { subject: 'Epistles', credits: 3 },
            { subject: 'Sunday School & VBS', credits: 2 },
          ],
          'Sem IV': [
            { subject: 'OT Survey II', credits: 3 },
            { subject: 'Systematic Theology IV', credits: 3 },
            { subject: 'India Church History', credits: 3 },
            { subject: 'Christian Ethics', credits: 3 },
            { subject: 'English IV', credits: 2 },
            { subject: 'History of Israel', credits: 3 },
            { subject: 'Prison Epistles', credits: 2 },
            { subject: 'Hermeneutics', credits: 3 },
          ],
        },
        'Third Year': {
          'Sem V': [
            { subject: 'OT Interpretation', credits: 3 },
            { subject: 'Doctrine of God & Man/Holy Spirit', credits: 3 },
            { subject: 'Early Church History', credits: 3 },
            { subject: 'Biblical Foundation of Mission', credits: 2 },
            { subject: 'Sunday School Ministry', credits: 2 },
            { subject: 'Homiletics I', credits: 3 },
            { subject: 'Bible Geography', credits: 2 },
            { subject: 'Research Methodology', credits: 3 },
          ],
          'Sem VI': [
            { subject: 'NT Interpretation', credits: 3 },
            { subject: 'Eschatology', credits: 3 },
            { subject: 'Medieval Church History', credits: 3 },
            { subject: 'Youth Ministry', credits: 2 },
            { subject: 'World Mission', credits: 2 },
            { subject: 'Homiletics II', credits: 3 },
            { subject: 'Practical Ministry', credits: 3 },
            { subject: 'Thesis Writing (B.Th.)', credits: 3 },
          ],
        },
      },
    },
    {
      id: 'mdiv',
      name: 'Master of Divinity (M.Div.)',
      description: 'Advanced theological education for ministry leadership',
      image: '/placeholder-program2.jpg',
      syllabus: {
        'First Year': {
          'Sem I': [
            { subject: 'OT Interpretation', credits: 3 },
            { subject: 'Systematic Theology I', credits: 3 },
            { subject: 'Early Church History', credits: 3 },
            { subject: 'Biblical Foundation of Mission', credits: 2 },
            { subject: 'Major Prophets', credits: 2 },
            { subject: 'General Epistle', credits: 2 },
            { subject: 'Christology', credits: 2 },
            { subject: 'NT Theology', credits: 3 },
          ],
          'Sem II': [
            { subject: 'NT Interpretation', credits: 3 },
            { subject: 'Systematic Theology II', credits: 3 },
            { subject: 'Medieval Church History', credits: 3 },
            { subject: 'Eschatology', credits: 2 },
            { subject: 'Minor Prophets', credits: 2 },
            { subject: 'Soteriology', credits: 2 },
            { subject: 'Pauline Epistles', credits: 2 },
            { subject: 'Christian Ethics', credits: 2 },
          ],
        },
        'Second Year': {
          'Sem III': [
            { subject: 'Systematic Theology III', credits: 3 },
            { subject: 'Reformation History', credits: 2 },
            { subject: 'Christian Apologetics', credits: 2 },
            { subject: 'Christian Leadership', credits: 2 },
            { subject: 'Ecclesiology', credits: 2 },
            { subject: 'Exegesis on Romans', credits: 2 },
            { subject: 'Christian Counselling', credits: 2 },
            { subject: 'Research Methodology', credits: 2 },
          ],
          'Sem IV': [
            { subject: 'Systematic Theology IV', credits: 3 },
            { subject: 'Modern Church History', credits: 3 },
            { subject: 'Personal Discipleship', credits: 2 },
            { subject: 'Doctrine of God & Man', credits: 2 },
            { subject: 'Pastoral Ministry', credits: 2 },
            { subject: 'Wisdom literature', credits: 2 },
            { subject: 'Practical Ministry', credits: 2 },
            { subject: 'Thesis Writing', credits: 3 },
          ],
        },
      },
    },
    {
      id: 'mth',
      name: 'Master of Theology (M.Th.)',
      description: 'Specialized theological research and advanced study',
      image: '/placeholder-program3.jpg',
      syllabus: {
        'First Year': {
          'Sem I': [
            { subject: 'Bible and Theology', credits: 3 },
            { subject: 'Theological Hermeneutics', credits: 3 },
            { subject: 'History of Christian Theology', credits: 3 },
            { subject: 'Advanced Systematic Theology I', credits: 4 },
            { subject: 'Themes and Theology of OT', credits: 3 },
          ],
          'Sem II': [
            { subject: 'Comparative Religions', credits: 3 },
            { subject: 'Contemporary Theology', credits: 3 },
            { subject: 'Contextual Theology', credits: 3 },
            { subject: 'Advanced Systematic Theology II', credits: 4 },
            { subject: 'Themes and Theology of NT', credits: 3 },
          ],
        },
        'Second Year': {
          'Sem III': [
            { subject: 'Pauline Theology', credits: 3 },
            { subject: 'Hermeneutics', credits: 3 },
            { subject: 'Anthropology and Hamartiology', credits: 3 },
            { subject: 'Advanced Systematic Theology III', credits: 4 },
            { subject: 'Research Methodology', credits: 3 },
          ],
          'Sem IV': [
            { subject: 'Homiletics', credits: 3 },
            { subject: 'Doctrinal Theology: God, Revelation and Creation', credits: 4 },
            { subject: 'Advanced Systematic Theology IV', credits: 3 },
            { subject: 'Practical Ministry', credits: 3 },
            { subject: 'Thesis (M.Th.)', credits: 4 },
          ],
        },
      },
    },
  ],
  counselling: [
    {
      id: 'dcc',
      name: 'Diploma in Christian Counselling',
      description: 'Foundation course in Christian counselling principles',
      image: '/placeholder-counselling1.jpg',
      syllabus: {
        'Content': 'Will be updated soon',
      },
    },
    {
      id: 'bcc',
      name: 'Bachelor of Christian Counselling',
      description: 'Comprehensive undergraduate program in Christian counselling',
      image: '/placeholder-counselling2.jpg',
      syllabus: {
        'First Year': {
          'Sem I': [
            { subject: 'Introduction: Psychology', credits: 3 },
            { subject: 'Theological Foundation', credits: 3 },
            { subject: 'Church History I', credits: 3 },
            { subject: 'English I', credits: 2 },
            { subject: 'Counselling Methodology I', credits: 2 },
            { subject: 'Life of Christ', credits: 2 },
            { subject: 'Church Ministry', credits: 2 },
            { subject: 'Christian Counselling', credits: 2 },
          ],
          'Sem II': [
            { subject: 'Biblical Counselling', credits: 3 },
            { subject: 'Pastoral Counselling', credits: 3 },
            { subject: 'Church History II', credits: 3 },
            { subject: 'English II', credits: 2 },
            { subject: 'Counselling Methodology II', credits: 3 },
            { subject: 'Outreach Ministry', credits: 2 },
            { subject: 'Teaching Method', credits: 2 },
            { subject: 'Christian Lay Counselling/Care', credits: 2 },
          ],
        },
        'Second Year': {
          'Sem III': [
            { subject: 'Theology of Counselling I', credits: 3 },
            { subject: 'Theology & Psychology', credits: 3 },
            { subject: 'Contemporary Church History', credits: 3 },
            { subject: 'Christian Evidence', credits: 2 },
            { subject: 'Biblical View of Individuals', credits: 2 },
            { subject: 'Biblical view of Marriage', credits: 3 },
            { subject: 'Biblical View of Family', credits: 3 },
            { subject: 'Family System Theory', credits: 2 },
          ],
          'Sem IV': [
            { subject: 'Theology of Counselling II', credits: 3 },
            { subject: 'Psychology & Spirituality', credits: 3 },
            { subject: 'Personality Theory & Research', credits: 3 },
            { subject: 'Christian Ethics', credits: 3 },
            { subject: 'Relationships & Research', credits: 2 },
            { subject: 'Christian Psychiatry & Psychology', credits: 3 },
            { subject: 'Pastoral care', credits: 2 },
            { subject: 'Counselling: Culture and Context', credits: 3 },
          ],
        },
        'Third Year': {
          'Sem V': [
            { subject: 'Cognitive Theoretical Framework', credits: 3 },
            { subject: 'Doctrine of God & Man/Holy Spirit', credits: 3 },
            { subject: 'Characteristics of effective counsellors', credits: 2 },
            { subject: 'Counselling processes', credits: 2 },
            { subject: 'Behaviour and Cognitive-Behaviour Therapies', credits: 3 },
            { subject: 'Foundations Of Social Behaviour', credits: 2 },
            { subject: 'Research Methodology', credits: 3 },
          ],
          'Sem VI': [
            { subject: 'Affective, Relational and Emotional Theories and Therapies', credits: 3 },
            { subject: 'Stress Management', credits: 3 },
            { subject: 'Mental Health Education', credits: 3 },
            { subject: 'Special Group Counselling', credits: 2 },
            { subject: 'Issues of Christian Counselling', credits: 2 },
            { subject: 'Counselling Skills', credits: 3 },
            { subject: 'Case studies in Psychological Research & Apologetics', credits: 3 },
            { subject: 'Thesis Writing (B.A.)', credits: 3 },
          ],
        },
      },
    },
    {
      id: 'ma-counselling',
      name: 'MA in Counselling Psychology',
      description: 'Advanced study in Christian counselling and psychology',
      image: '/placeholder-counselling3.jpg',
      syllabus: {
        'First Year': {
          'Sem I': [
            { subject: 'Systematic Theology I', credits: 3 },
            { subject: 'Biblical Counselling', credits: 3 },
            { subject: 'Counselling Methodology I', credits: 3 },
            { subject: 'Christian Counselling', credits: 2 },
            { subject: 'Theology & Psychology', credits: 2 },
            { subject: 'Stress Management', credits: 2 },
            { subject: 'Cognitive Theoretical Framework', credits: 2 },
            { subject: 'Emotional Theories', credits: 3 },
          ],
          'Sem II': [
            { subject: 'Systematic Theology II', credits: 3 },
            { subject: 'Pastoral Counselling', credits: 3 },
            { subject: 'Counselling Methodology II', credits: 3 },
            { subject: 'Christian Lay Counselling/Care', credits: 2 },
            { subject: 'Psychology & Spirituality', credits: 2 },
            { subject: 'Christian Ethics', credits: 2 },
            { subject: 'Foundations Of Social Behaviour', credits: 2 },
            { subject: 'Counselling Skills', credits: 2 },
          ],
        },
        'Second Year': {
          'Sem III': [
            { subject: 'Systematic Theology III', credits: 3 },
            { subject: 'Counselling Theories and Strategies', credits: 2 },
            { subject: 'Marriage and Family Therapy', credits: 2 },
            { subject: 'Group Counselling Dynamics', credits: 2 },
            { subject: 'counselling ethics', credits: 2 },
            { subject: 'Counselling processes', credits: 2 },
            { subject: 'Psychology of Religion', credits: 2 },
            { subject: 'Research Methodology', credits: 2 },
          ],
          'Sem IV': [
            { subject: 'Systematic Theology IV', credits: 3 },
            { subject: 'Conflict Management and Resolution', credits: 3 },
            { subject: 'Personality Theory & Research', credits: 2 },
            { subject: 'Mental Health Education', credits: 2 },
            { subject: 'Issues of Christian Counselling', credits: 2 },
            { subject: 'Case studies in Psychological Research & Apologetics', credits: 2 },
            { subject: 'Practical Ministry', credits: 2 },
            { subject: 'Thesis Writing', credits: 3 },
          ],
        },
      },
    },
  ],
};
